name: Main Workflow

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Set up JDK
       uses: actions/setup-java@v2
       with:
         distribution: microsoft
         java-version: '17.0.1'
     - name: Build with Gradle
       run: ./gradlew shadowJar
     - name: Archive build artifacts
       uses: actions/upload-artifact@v2
       with:
         name: build-artifacts
         path: build/libs/
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Download build Artifacts
       uses: actions/download-artifact@v2
       with:
         name: build-artifacts
     - name: List Artifacts
       run: |
         ls -R .
