name: Main Workflow

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Set up JDK
       uses: actions/setup-java@v2
       with:
         distribution: microsoft
         java-version: '17.0.1'
     - name: Build with Gradle
       run: ./gradlew shadowJar
     - name: Archive build artifacts
       uses: actions/upload-artifact@v2
       with:
         name: build-artifacts
         path: build/libs/
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Download build Artifacts
       uses: actions/download-artifact@v2
       with:
         name: build-artifacts
         path: build/libs/
     - name: Create docker image
       run: |
         docker build -t discord-bot .
     - name: Login into docker
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.DISCORD_BOT_SECRET_V1 }}
     - name: Tag docker image
       run: |
         docker tag discord-bot ghcr.io/${{ github.repository }}:latest
     - name: Push docker image
       run: |
         docker push ghcr.io/${{ github.repository }}:latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Test step
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DISCORD_BOT_HOST }}
          port: ${{ secrets.DISCORD_BOT_PORT }}
          username: ${{ secrets.DISCORD_BOT_USER }}
          password: ${{ secrets.DISCORD_BOT_PASS }}
          script: |
            echo ${{ secrets.DISCORD_BOT_SECRET_V1 }} | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop discord-bot || true && docker rm discord-bot || true
            docker run -d --name discord-bot ghcr.io/${{ github.repository }}:latest ${{ secrets.MAIN_TOKEN }}